apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-java-db-password
  namespace: this-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: teams-dev/this-dev/DB_PASSWORD
