# syntax=docker/dockerfile:1
# Generated by DeepAgent. Rerunning the deploy regenerates this file — delete this line to keep your own edits.
# --- Build stage: produce the executable JAR ---
FROM eclipse-temurin:21-jdk AS builder
WORKDIR /src
COPY . .
# Maven when pom.xml is present, otherwise Gradle. Wrappers win when shipped.
RUN set -eu; \
    if [ -f pom.xml ]; then \
      if [ -f mvnw ]; then chmod +x mvnw && ./mvnw -B -DskipTests package; \
      else \
        apt-get update && apt-get install -y --no-install-recommends maven && rm -rf /var/lib/apt/lists/*; \
        mvn -B -DskipTests package; \
      fi; \
    elif [ -f gradlew ]; then \
      chmod +x gradlew && ./gradlew --no-daemon -x test bootJar || ./gradlew --no-daemon -x test build; \
    else \
      apt-get update && apt-get install -y --no-install-recommends gradle && rm -rf /var/lib/apt/lists/*; \
      gradle --no-daemon -x test build; \
    fi
# Collect the ONE runnable artifact. Gradle emits -plain.jar alongside the real
# boot jar; picking the largest non-plain jar avoids launching the empty one.
RUN set -eu; mkdir -p /out; \
    jar="$(find . -type f -name '*.jar' ! -name '*-plain.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar' \
             -printf '%s %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-)"; \
    if [ -z "$jar" ]; then echo "No runnable JAR produced by the build" >&2; exit 1; fi; \
    cp "$jar" /out/app.jar

# --- Runtime: JRE only, non-root ---
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /out/app.jar /app/app.jar
# Numeric USER — runAsNonRoot rejects names (see PYTHON template note).
RUN useradd -r -u 10001 appuser && chown -R appuser /app
USER 10001
EXPOSE 8080
# 75.0, not 75: Java 8 declares MaxRAMPercentage a double and refuses an
# integer ("Improperly specified VM option 'MaxRAMPercentage=75'" — the JVM
# never starts). Every later Java accepts 75.0 too.
ENV JAVA_OPTS="-XX:MaxRAMPercentage=75.0"
ENTRYPOINT ["sh","-c","exec java $JAVA_OPTS -jar /app/app.jar"]
